replicaCount: 1

image:
  repository: munirathnakumar/mlops-task4
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

nodeSelector: {}

tolerations: []

affinity: {}
